services:
  primary:
    image: postgres:15.0
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PRIMARY_NAME:-postgres}
      - POSTGRES_USER=${PRIMARY_USER:-postgres}
      - POSTGRES_PASSWORD=${PRIMARY_PASSWORD?Variable not set}
    command: -c 'config_file=/config/postgresql.conf'
    volumes:
      - ${PWD}/primary/pgdata:/var/lib/postgresql/data
      - ${PWD}/primary/config:/config
      - ${PWD}/primary/archive:/mnt/server/archive
    container_name: primary

  standby:
    image: postgres:15.0
    env_file: .env
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${STANDBY_NAME:-postgres}
      - POSTGRES_USER=${STANDBY_USER:-postgres}
      - POSTGRES_PASSWORD=${STANDBY_PASSWORD?Variable not set}
    command: -c 'config_file=/config/postgresql.conf'
    volumes:
      - ${PWD}/standby/pgdata:/var/lib/postgresql/data
      - ${PWD}/standby/config:/config
      - ${PWD}/standby/archive:/mnt/server/archive
    container_name: standby
  read:
    image: postgres:15.0
    env_file: .env
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=${READ_NAME:-postgres}
      - POSTGRES_USER=${READ_USER:-postgres}
      - POSTGRES_PASSWORD=${READ_PASSWORD?Variable not set}
    command: -c 'config_file=/config/postgresql.conf'
    volumes:
      - ${PWD}/read/pgdata:/var/lib/postgresql/data
      - ${PWD}/read/config:/config
      - ${PWD}/read/archive:/mnt/server/archive
    container_name: read
