services:
  primary:
    image: postgres:alpine3.21
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PRIMARY_NAME:-postgres}
      - POSTGRES_USER=${PRIMARY_USER:-postgres}
      - POSTGRES_PASSWORD=${PRIMARY_PASSWORD?Variable not set}
    volumes:
      - primary_data:/var/lib/postgresql

  standby:
    image: postgres:alpine3.21
    env_file: .env
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${STANDBY_NAME:-postgres}
      - POSTGRES_USER=${STANDBY_USER:-postgres}
      - POSTGRES_PASSWORD=${STANDBY_PASSWORD?Variable not set}
    volumes:
      - standby_data:/var/lib/postgresql
  read:
    image: postgres:alpine3.21
    env_file: .env
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=${READ_NAME:-postgres}
      - POSTGRES_USER=${READ_USER:-postgres}
      - POSTGRES_PASSWORD=${READ_PASSWORD?Variable not set}
    volumes:
      - read_data:/var/lib/postgresql
    read_only: true

volumes:
  primary_data:
  standby_data:
  read_data:
