# docker-compose.yml
version: '3.8'
services:
  primary:
    image: postgres:15
    container_name: primary
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - postgres_network
    command: |
      postgres 
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c listen_addresses='*'

  standby:
    image: postgres:15
    container_name: standby
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - standby_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    depends_on:
      - primary
    command: |
      tail -f /dev/null

  replica:
    image: postgres:15
    container_name: replica
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - replica_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    depends_on:
      - primary
    command: |
      tail -f /dev/null

volumes:
  primary_data:
  standby_data:
  replica_data:

networks:
  postgres_network:
    driver: bridge